# Generated by Django 2.2 on 2019-05-09 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pierdoly', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miasto', models.CharField(max_length=30)),
                ('data_wniosku', models.DateTimeField(auto_now_add=True)),
                ('poczatek', models.DateTimeField()),
                ('koniec', models.DateTimeField()),
                ('kraj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pierdoly.Country')),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Delegacje',
            },
        ),
    ]
