# Generated by Django 2.2 on 2019-05-13 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pierdoly', '0004_finalpaymenttype'),
        ('delegacja', '0002_plannedexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealizedExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delegacja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delegacja.BusinessTrip')),
                ('rodzaj_wydatku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pierdoly.ExpenseType')),
                ('rodzaj_zrealizowanej_platnosci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pierdoly.FinalPaymentType')),
                ('waluta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pierdoly.Currency')),
            ],
            options={
                'verbose_name_plural': 'Zrealizowane wydatki',
            },
        ),
    ]
