# Generated by Django 2.2 on 2019-05-13 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pierdoly', '0004_finalpaymenttype'),
        ('delegacja', '0003_realizedexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='StayAbroad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poczatek', models.DateTimeField()),
                ('koniec', models.DateTimeField()),
                ('delegacja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delegacja.BusinessTrip')),
                ('kraj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pierdoly.Country')),
            ],
            options={
                'verbose_name_plural': 'Pobyt zagranicą',
            },
        ),
    ]
