# Generated by Django 2.2 on 2019-05-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegacja', '0004_stayabroad'),
    ]

    operations = [
        migrations.AddField(
            model_name='realizedexpense',
            name='dokument1',
            field=models.ImageField(blank=True, null=True, upload_to='faktury/'),
        ),
        migrations.AddField(
            model_name='realizedexpense',
            name='dokument2',
            field=models.ImageField(blank=True, null=True, upload_to='faktury/'),
        ),
        migrations.AddField(
            model_name='realizedexpense',
            name='dokument3',
            field=models.ImageField(blank=True, null=True, upload_to='faktury/'),
        ),
    ]
