# Generated by Django 2.2 on 2019-05-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegacja', '0006_auto_20190519_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realizedexpense',
            name='akceptacja_planowanej',
        ),
        migrations.RemoveField(
            model_name='realizedexpense',
            name='akceptacja_zrealizowanej',
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='akceptacja_planowanej',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='akceptacja_zrealizowanej',
            field=models.BooleanField(default=False),
        ),
    ]
