# Generated by Django 2.2 on 2019-05-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegacja', '0007_auto_20190519_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstrip',
            name='do_managera',
            field=models.BooleanField(default=False),
        ),
    ]
