# Generated by Django 2.2 on 2019-05-21 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delegacja', '0008_businesstrip_do_managera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstrip',
            name='pracownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pierdoly.Employee'),
        ),
    ]
