# Generated by Django 2.2 on 2019-05-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegacja', '0010_auto_20190522_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstrip',
            name='realizacja_księgowość',
        ),
        migrations.AlterField(
            model_name='realizedexpense',
            name='dokument1',
            field=models.FileField(blank=True, null=True, upload_to='faktury/'),
        ),
        migrations.AlterField(
            model_name='realizedexpense',
            name='dokument2',
            field=models.FileField(blank=True, null=True, upload_to='faktury/'),
        ),
        migrations.AlterField(
            model_name='realizedexpense',
            name='dokument3',
            field=models.FileField(blank=True, null=True, upload_to='faktury/'),
        ),
    ]
