# Generated by Django 2.2 on 2019-05-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegacja', '0014_auto_20190522_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizedexpense',
            name='dokument1',
            field=models.FileField(blank=True, default=True, upload_to='faktury/'),
        ),
        migrations.AlterField(
            model_name='realizedexpense',
            name='dokument2',
            field=models.FileField(blank=True, upload_to='faktury/'),
        ),
        migrations.AlterField(
            model_name='realizedexpense',
            name='dokument3',
            field=models.FileField(blank=True, upload_to='faktury/'),
        ),
    ]
