# Generated by Django 2.2 on 2019-05-23 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegacja', '0016_auto_20190522_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstrip',
            name='koniec',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='poczatek',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
