# Generated by Django 2.2 on 2019-05-23 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegacja', '0017_auto_20190523_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstrip',
            name='koniec',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 8, 34, 0, 421882)),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='poczatek',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 8, 34, 0, 421882)),
        ),
    ]
