# Generated by Django 2.2 on 2019-05-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pierdoly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wydatek', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Rodzaje wydatków',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sposob_platnosci', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Rodzaje płatności',
            },
        ),
    ]
