# Generated by Django 2.2 on 2019-05-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pierdoly', '0002_expensetype_paymenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='dzienna_kwota',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
            preserve_default=False,
        ),
    ]
