# Generated by Django 2.2 on 2019-05-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pierdoly', '0003_country_dzienna_kwota'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalPaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sposob_zrealizowanej_platnosci', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Rodzaje ostatecznych płatności',
            },
        ),
    ]
