# Generated by Django 2.2 on 2019-05-14 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pierdoly', '0005_employee_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='projekt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pierdoly.Project'),
        ),
    ]
