# Generated by Django 2.2 on 2019-05-14 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pierdoly', '0006_auto_20190514_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='kierownik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
